In [2]:
import numpy as np 

## LE1
#### Eigenwerte, Eigenraum, Eigenvektoren

In [8]:
A = np.array([[0, 0, -2], [1, 2, 1], [1, 0, 3]])
eigenwerte, eigenvektoren = np.linalg.eig(A)
eigenwerte, eigenvektoren

(array([2., 1., 2.]),
 array([[ 0.        , -0.81649658,  0.706555  ],
        [ 1.        ,  0.40824829,  0.03949763],
        [ 0.        ,  0.40824829, -0.706555  ]]))

In [9]:
eigenvektoren[:, 0]

array([0., 1., 0.])

#### Diagonalisierung

In [12]:
D = np.diag(eigenwerte)
V = eigenvektoren
Vinv = np.linalg.inv(V)
D, V, Vinv

(array([[2., 0., 0.],
        [0., 1., 0.],
        [0., 0., 2.]]),
 array([[ 0.        , -0.81649658,  0.706555  ],
        [ 1.        ,  0.40824829,  0.03949763],
        [ 0.        ,  0.40824829, -0.706555  ]]),
 array([[ 1.0559017 ,  1.        ,  1.1118034 ],
        [-2.44948974, -0.        , -2.44948974],
        [-1.41531799, -0.        , -2.83063597]]))

In [15]:
Aindirekt = V.dot(D.dot(Vinv))
print(A, Aindirekt)
np.testing.assert_almost_equal(A, Aindirekt)

[[ 0  0 -2]
 [ 1  2  1]
 [ 1  0  3]] [[-1.24420965e-16  0.00000000e+00 -2.00000000e+00]
 [ 1.00000000e+00  2.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00  0.00000000e+00  3.00000000e+00]]


Matrix-Quadrat via Diagonalisierung

In [16]:
n = 2
Dpower = np.linalg.matrix_power(D, n)
Apower = V.dot(Dpower.dot(Vinv))
Apower

array([[-2.,  0., -6.],
       [ 3.,  4.,  3.],
       [ 3.,  0.,  7.]])

## LE2
#### Positiv Definit

In [18]:
print(np.all(eigenwerte>0))

True


## LE 4
#### Normen Vektoren

In [19]:
B = np.array([0, 2, -1])

In [24]:
print("Euklidisch: ", np.linalg.norm(B))
print("Manhattan/L1: ", np.linalg.norm(B, ord = 1))
print("L0: ", np.linalg.norm(B, ord = 0))
print("Max: ", np.linalg.norm(B, ord = np.inf))

Euklidisch:  2.23606797749979
Manhattan/L1:  3.0
L0:  2.0
Max:  2.0


#### Normen Matrizen

In [33]:
print("Frobenius: ", np.linalg.norm(A))
print("Summennorm: ", np.sum(np.abs(A)))
print("Spaltensummen: ", np.linalg.norm(A, ord = 1))
print("Spaltensummen: ", np.max(np.sum(np.abs(A), axis = 0)))
print("Spektralnorm: ", np.linalg.norm(A, ord = 2))
print("Zwischensummennorm: ", np.linalg.norm(A, ord = np.inf))
print("Zeilensummen: ", np.max(np.sum(np.abs(A), axis = 1)))

Frobenius:  4.47213595499958
Summennorm:  10
Spaltensummen:  6.0
Spaltensummen:  6
Spektralnorm:  3.968118785068667
Zwischensummennorm:  4.0
Zeilensummen:  4


## LE5
#### Singulärwertzerlegung

In [ ]:
# Import Image
# C = plt.imread("noise.jpg")
# plt.imshow(C, cmap = "gray")

In [35]:
C = np.array([[1, 2, 3, 4],
    [49, 5, 60, 4],
    [79, 8, 9, 4],
    [1, 28, 3, 4]])
C

array([[ 1,  2,  3,  4],
       [49,  5, 60,  4],
       [79,  8,  9,  4],
       [ 1, 28,  3,  4]])

In [39]:
U, E, V = np.linalg.svd(C, full_matrices=False)
U.shape, E.shape, V.shape
Cnew = U.dot(np.diag(E).dot(V))
print(Cnew)
np.testing.assert_almost_equal(C, Cnew)

[[ 1.  2.  3.  4.]
 [49.  5. 60.  4.]
 [79.  8.  9.  4.]
 [ 1. 28.  3.  4.]]


In [42]:
def truncated_SVD(U, E, V, k):
    U = U[:,:k]
    E = np.diag(E[:k])
    V = V[:k]
    ACnew2 = U.dot(E.dot(V))
    print(ACnew2)

lst = [1, 2, 5]

for x in lst:
    truncated_SVD(U, E, V, x)

[[ 2.37780275  0.28089201  1.2624338   0.15600899]
 [62.84595216  7.42404967 33.36645743  4.12335872]
 [65.36663498  7.72182023 34.70474976  4.28874216]
 [ 4.74016566  0.55996009  2.51667021  0.31100497]]
[[ 1.35067753  0.2453069   3.2019122   0.18058226]
 [48.78554788  6.93692205 59.91614188  4.45974426]
 [78.98238354  8.1935426   8.99469046  3.9629947 ]
 [ 3.91026421  0.53120787  4.08373905  0.33085979]]
[[ 1.  2.  3.  4.]
 [49.  5. 60.  4.]
 [79.  8.  9.  4.]
 [ 1. 28.  3.  4.]]
